version: "3.8"

services:
  fastapi-ai:
    build: .
    container_name: safefam-ai-server
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    environment:
      ENV: local
      RABBITMQ_URL: ${RABBITMQ_DOCKER_URL:-amqp://safefam:safefam-local@rabbitmq:5672/}
      RABBITMQ_ANALYSIS_EXCHANGE: ${RABBITMQ_ANALYSIS_EXCHANGE:-safefam.analysis}
      RABBITMQ_ANALYSIS_REQUEST_QUEUE: ${RABBITMQ_ANALYSIS_REQUEST_QUEUE:-safefam.analysis.requested.q}
      RABBITMQ_ANALYSIS_REQUEST_ROUTING_KEY: ${RABBITMQ_ANALYSIS_REQUEST_ROUTING_KEY:-analysis.requested.v1}
      RABBITMQ_PREFETCH_COUNT: ${RABBITMQ_PREFETCH_COUNT:-1}
      RABBITMQ_CONSUMER_ENABLED: ${RABBITMQ_CONSUMER_ENABLED:-true}
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
    networks:
      - safefam-network

networks:
  safefam-network:
    external: true
    name: safefam-network
